services:
    frontend:
        build: ./frontend
        container_name: next_frontend
        ports:
            - "3000:3000" # Serve frontend on localhost:3000
        env_file:
            - ./frontend/.env # Load environment variables from frontend .env file
        develop:
            watch:
                - action: sync
                  path: ./frontend/src
                  target: /app
                - action: rebuild
                  path: ./frontend/package.json
        depends_on:
            - backend

    backend:
        build: ./backend
        container_name: node_backend
        ports:
            - "5000:5000" # Backend runs on port 5000
        env_file:
            - ./backend/.env # Load environment variables from backend .env file
        develop:
            watch:
                - action: rebuild
                  path: ./backend
                  target: /app
                - action: rebuild
                  path: ./backend/package.json
        depends_on:
            - mongodb
        volumes:
            - ./backend/logs:/app/logs
            - ./backend/repoCloning:/app/repoCloning
    mongodb:
        image: mongodb/mongodb-atlas-local:8.0.6
        container_name: mongo_database
        hostname: mongo_database
        restart: unless-stopped
        ports:
            - "27017:27017"
        env_file:
            - ./database/.env # Load environment variables from database .env file
        volumes:
            # Mount data directory for persistence
            - mongo_data:/data/db
            - mongo_configdb:/data/configdb
volumes:
    mongo_data:
    mongo_configdb:
